version: '3'

services:
  bitbucket:
    image: nicoherbigio/atlassian-bitbucket-server:5.6
    restart: always
    depends_on:
      - bitbucket-database
    networks:
      - frontend
      - backend
    ports:
      - 7990:7990
      - 7999:7999
    volumes:
      - bitbucket-data:/var/atlassian/bitbucket
    environment:
      - JVM_MINIMUM_MEMORY=${BITBUCKET_JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${BITBUCKET_JVM_MAXIMUM_MEMORY}
      - CATALINA_CONNECTOR_SECURE=${BITBUCKET_CONNECTOR_SECURE}
      - CATALINA_CONNECTOR_SCHEME=${BITBUCKET_CONNECTOR_SCHEME}
      - CATALINA_CONNECTOR_PROXYNAME=${BITBUCKET_CONNECTOR_PROXY_NAME}
      - CATALINA_CONNECTOR_PROXYPORT=${BITBUCKET_CONNECTOR_PROXY_PORT}
      - SERVER_SECURE=${BITBUCKET_CONNECTOR_SECURE}
      - SERVER_SCHEME=${BITBUCKET_CONNECTOR_SCHEME}
      - SERVER_PROXY_NAME=${BITBUCKET_CONNECTOR_PROXY_NAME}
      - SERVER_PROXY_PORT=${BITBUCKET_CONNECTOR_PROXY_PORT}

  bitbucket-database:
    image: postgres:9.6
    restart: always
    networks:
      - backend
    volumes:
      - ./services/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - bitbucket-database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BITBUCKET_DATABASE_NAME=${BITBUCKET_DATABASE_NAME}
      - BITBUCKET_DATABASE_USER=${BITBUCKET_DATABASE_USER}
      - BITBUCKET_DATABASE_PASSWORD=${BITBUCKET_DATABASE_PASSWORD}

networks:
  frontend:
  backend:

volumes:
  bitbucket-data:
  bitbucket-database-data:
